name: sandwich_shop
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
description: "A Flutter project for a sandwich shop."
=======
description: "A new Flutter project."
>>>>>>> 816cadc (first commit)
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
=======
description: "A Flutter project for a sandwich shop."
publish_to: none
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

version: 1.0.0+1

environment:
<<<<<<< HEAD
<<<<<<< HEAD
  sdk: ">=2.17.0 <4.0.0"
=======
  sdk: ^3.7.2
>>>>>>> 816cadc (first commit)
=======
  sdk: ">=2.17.0 <4.0.0"
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
<<<<<<< HEAD
  cupertino_icons: ^1.0.0
=======
  cupertino_icons: ^1.0.8
>>>>>>> 816cadc (first commit)
=======
  cupertino_icons: ^1.0.0
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)
=======
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
=======
description: "A Flutter project for a sandwich shop."
publish_to: none
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
=======
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
=======
description: "A Flutter project for a sandwich shop."
publish_to: none
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
>>>>>>> 816cadc (first commit)

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
<<<<<<< HEAD
>>>>>>> 816cadc (first commit)
=======
  cupertino_icons: ^1.0.0
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)
=======
>>>>>>> 816cadc (first commit)
=======
  cupertino_icons: ^1.0.0
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

dev_dependencies:
  flutter_test:
    sdk: flutter

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 816cadc (first commit)
=======
>>>>>>> 816cadc (first commit)
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  flutter_lints: ^2.0.0
=======
  flutter_lints: ^5.0.0
>>>>>>> 816cadc (first commit)
=======
  flutter_lints: ^2.0.0
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

flutter:
  uses-material-design: true
  assets:
<<<<<<< HEAD
<<<<<<< HEAD
    - assets/images/
=======
  flutter_lints: ^5.0.0
=======
  flutter_lints: ^2.0.0
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

flutter:
  uses-material-design: true
<<<<<<< HEAD
=======
  flutter_lints: ^5.0.0
=======
  flutter_lints: ^2.0.0
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

flutter:
  uses-material-design: true
<<<<<<< HEAD
>>>>>>> 816cadc (first commit)

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
<<<<<<< HEAD
>>>>>>> 816cadc (first commit)
=======
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)
=======
    - assets/images/
>>>>>>> cbb25ee (Add assets to pubspec)
=======
>>>>>>> 816cadc (first commit)
=======
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)
=======
    - assets/images/
>>>>>>> cbb25ee (Add assets to pubspec)
