name: sandwich_shop
<<<<<<< HEAD
<<<<<<< HEAD
description: "A Flutter project for a sandwich shop."
=======
description: "A new Flutter project."
>>>>>>> 816cadc (first commit)
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
=======
description: "A Flutter project for a sandwich shop."
publish_to: none
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

version: 1.0.0+1

environment:
<<<<<<< HEAD
<<<<<<< HEAD
  sdk: ">=2.17.0 <4.0.0"
=======
  sdk: ^3.7.2
>>>>>>> 816cadc (first commit)
=======
  sdk: ">=2.17.0 <4.0.0"
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
<<<<<<< HEAD
  cupertino_icons: ^1.0.0
=======
  cupertino_icons: ^1.0.8
>>>>>>> 816cadc (first commit)
=======
  cupertino_icons: ^1.0.0
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

dev_dependencies:
  flutter_test:
    sdk: flutter

<<<<<<< HEAD
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
<<<<<<< HEAD
  flutter_lints: ^2.0.0
=======
  flutter_lints: ^5.0.0
>>>>>>> 816cadc (first commit)
=======
  flutter_lints: ^2.0.0
>>>>>>> fb04541 (ğŸ“ Update pubspec.yaml and pubspec.lock for dependency version changes)

flutter:
  uses-material-design: true
  assets:
    - assets/images/